version: '3.1'

services:
  production-nginx-container:
    container_name: 'production-nginx-container'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf
      - ./site:/usr/share/nginx/html
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /mnt/docker-volumes/letsencrypt-docker-nginx/etc/letsencrypt/live/sensorcentral.heisterberg.dk/fullchain.pem:/etc/letsencrypt/live/sensorcentral.heisterberg.dk/fullchain.pem
      - /mnt/docker-volumes/letsencrypt-docker-nginx/etc/letsencrypt/live/sensorcentral.heisterberg.dk/privkey.pem:/etc/letsencrypt/live/sensorcentral.heisterberg.dk/privkey.pem
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

