version: '3.1'

services:
  prometheus:
    image: quay.io/prometheus/prometheus
    build:
      context: .
      args:
        config.file: /etc/prometheus/prometheus.yml
        storage.tsdb.path: /data/storage
        storage.tsdb.retention: 100d
        web.console.templates: /data/consoles
        web.console.libraries: /data/console_libraries
    ports: 
      - 9090:9090
    networks:
      - docker-network
    volumes:
      - ../../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /mnt/docker-volumes/prometheus:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - docker-network
    environment:
      GF_SECURITY_ADMIN_PASSWORD: W3yvU!AU^T1#wfq%
    volumes:
      - /mnt/docker-volumes/grafana:/var/lib/grafana
      - ../../config/grafana/conf:/etc/grafana
    depends_on:
      - prometheus

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../config/nginx/htpasswd:/etc/nginx/.htpasswd
      - ../../config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../config/nginx/site:/usr/share/nginx/html
      - ../../config/nginx/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /mnt/docker-volumes/letsencrypt-docker-nginx/etc/letsencrypt/live/sensorcentral.heisterberg.dk/fullchain.pem:/etc/letsencrypt/live/sensorcentral.heisterberg.dk/fullchain.pem
      - /mnt/docker-volumes/letsencrypt-docker-nginx/etc/letsencrypt/live/sensorcentral.heisterberg.dk/privkey.pem:/etc/letsencrypt/live/sensorcentral.heisterberg.dk/privkey.pem      
    networks:
      - docker-network
    depends_on:
       - grafana

networks:
  docker-network:
    driver: bridge

