version: '3.7'

services:
  nerdbox-prometheus:
    image: quay.io/prometheus/prometheus
    build:
      context: .
      args:
        config.file: /data/prometheus.yml
        storage.tsdb.path: /data/storage
        storage.tsdb.retention: 100d
        web.console.templates: /data/consoles
        web.console.libraries: /data/console_libraries
        web.external-url: http://localhost/prometheus/
        web.route-prefix: /
    ports: 
      - 9090:9090
    networks:
      - nerdbox-network
    volumes:
      - /tmp/docker-prometheus-data:/data

  nerdbox-grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - nerdbox-network
    volumes:
      - /tmp/docker-grafana-data:/var/lib/grafana
      - /tmp/docker-grafana-data/conf:/etc/grafana
      - /tmp/docker-grafana-data/plugins:/var/lib/grafana/plugins
    depends_on:
      - nerdbox-prometheus

  nerdbox-nginx:
    image: nginx:latest
    ports:
      - 80:80
    networks:
      - nerdbox-network
    volumes:
      - /tmp/docker-nginx-data:/etc/nginx:ro
    depends_on:
      - nerdbox-grafana

networks:
  nerdbox-network:
    driver: bridge

